### ISSUE TITLE
node的智能指针循环引用问题

### ISSUE THREAD

**Issue by 1461521844lijin** [sherlockchou86/video_pipe_c#31]
在想给作者的代码添加线程退出标识时，在实现析构时的优雅线程退出时发现
由于不同node与node的智能指针之间存在循环引用，导致资源不会被自动回收
当我删除智能指针时，启动的线程也不会被主动释放，会一直存在
![image](https://github.com/sherlockchou86/video_pipe_c/assets/34806114/be9d89b4-df97-42ad-ba74-675920517047)
节点连接部分的代码可以考虑优化一下

**Comment by sherlockchou86** [comment]
已修复
