### ISSUE TITLE
你好，请问下channel_index具体是什么作用？

### ISSUE THREAD

**Issue by BaofengZan** [sherlockchou86/video_pipe_c#4]
非常棒的工作，赞！
https://github.com/sherlockchou86/video_pipe_c/blob/1cc9956dc161fe621e829160263bc37ac41de7cb/nodes/vp_src_node.h#L34

**Comment by sherlockchou86** [comment]
> 非常棒的工作，赞！
> 
> https://github.com/sherlockchou86/video_pipe_c/blob/1cc9956dc161fe621e829160263bc37ac41de7cb/nodes/vp_src_node.h#L34

通道号，每个通道接入一路视频，可以多个通道合并在一起。
所以开头的src 和 结尾的des 节点需要知道自己是哪个通道。

可以跑一跑代码，有问题随时交流。

**Comment by BaofengZan** [comment]
> > 非常棒的工作，赞！
> > https://github.com/sherlockchou86/video_pipe_c/blob/1cc9956dc161fe621e829160263bc37ac41de7cb/nodes/vp_src_node.h#L34
> 
> 通道号，每个通道接入一路视频，可以多个通道合并在一起。 所以开头的src 和 结尾的des 节点需要知道自己是哪个通道。
> 
> 可以跑一跑代码，有问题随时交流。

感谢。我在你的博客里面添加你的微信，提示无法添加，能否建立一个群之类的，方便后来的人一起交流？

**Comment by sherlockchou86** [comment]
> > > 非常棒的工作，赞！
> > > https://github.com/sherlockchou86/video_pipe_c/blob/1cc9956dc161fe621e829160263bc37ac41de7cb/nodes/vp_src_node.h#L34
> > 
> > 
> > 通道号，每个通道接入一路视频，可以多个通道合并在一起。 所以开头的src 和 结尾的des 节点需要知道自己是哪个通道。
> > 可以跑一跑代码，有问题随时交流。
> 
> 感谢。我在你的博客里面添加你的微信，提示无法添加，能否建立一个群之类的，方便后来的人一起交流？

我微信最近炸号了，等等

**Comment by sherlockchou86** [comment]
vx:  zhzhi78
